- name: Tell you what I'm gona do
  debug:
    msg: "{{ config.files | json_query('[*].dst') }}"
  when: config is defined and config.files is defined

- name: Create config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items: "{{ config.directories }}"
  when: config is defined and config.directories is defined

- name: Copy configurations files
  copy:
    src: "{{ secrets_conf_root }}/files/{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode | default('0644') }}"
    backup: yes
  with_items: "{{ config.files }}"
  when: config is defined and config.files is defined

