- name: Install git-chglog
  include_tasks: ../../commons/tasks/get_github_binary.yml
  vars:
    package_name: git-chglog
    package_binary: git-chglog
    package_overwrite_existing: "{{ git_chglog_overwrite_existing | default(development_tools_overwrite_existing) }}"
    package_version: "{{ git_chglog_version | default(development_tools_version) }}"
    package_repository: git-chglog/git-chglog
    package_release_filename: 'git-chglog_@VERSION_linux_amd64'
    package_version_mutation: '| sed "s/^v\(.*\)/\1/"'

- name: check for mc installation
  stat:
    path: /usr/local/bin/mc
  changed_when: false
  register: mc_binary_exists
- when: not mc_binary_exists.stat.exists
  name: Install mc (minio cli)
  get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin/mc
    mode: '0777'
    owner: root
    group: root

- name: Install dive
  include_tasks: ../../commons/tasks/get_github_binary.yml
  vars:
    package_name: dive
    package_binary: dive
    package_overwrite_existing: "{{ dive_overwrite_existing | default(development_tools_overwrite_existing) }}"
    package_version: "{{ dive_version | default(development_tools_version) }}"
    package_repository: wagoodman/dive
    package_release_filename: 'dive_@VERSION_linux_amd64'
    package_version_mutation: '| sed "s/^v\(.*\)/\1/"'


