# vi: set ft=yaml.ansible :

- hosts: commons
  tags:
    - base
  become: yes
  roles:
    - name: base
      tags: ['apt']
    - name: oh_my_zsh
      tags: ['oh-my-zsh']
      become_user: "{{ user }}"
    - name: dotfiles
      tags: ['dotfiles']
      become_user: "{{ user }}"
    - name: authenticator
      tags: [ 'mfa' ]
    - name: ssh
      tags: [ 'ssh' ]
  environment:
    - "{{ proxy_env | default ({}) }}"

- hosts: commons_ui
  tags:
    - base
  become: yes
  roles:
    - name: base_ui
      tags: ['apt']
    - name: oefenweb.chrome
      tags: ['chrome']
    - name: intellij
      tags: ['intellij']
  environment:
    - "{{ proxy_env | default ({}) }}"

- hosts: home
  tags:
    - tools
  roles:
    - name: nas
      tags: [ 'nas' ]
    - name: mailer
      tags: [ 'mailer' ]
    - name: scheduled_tasks
      tags: [ 'scheduled_tasks' ]
    - name: web_privacy_proxy
      tags: [ 'web_privacy_proxy' ]
  environment:
    - "{{ proxy_env | default ({}) }}"

- hosts: devbox
  tags:
    - devbox
  become: yes
  roles:
    - name: docker
      tags: [ 'docker' ]
    - name: java
      tags: [ 'java' ]
    - name: nvm
      tags: [ 'nvm' ]
      become_user: "{{ user }}"
  environment:
    - "{{ proxy_env | default ({}) }}"

- hosts: home
  tags:
    - devbox
  become: yes
  roles:
    - name: nodejs
      tags: [ 'nodejs' ]
      become_user: "{{ user }}"

