# vi: set ft=ansible :

- hosts: commons
  tags:
    - base
  roles:
    - name: base
      tags: ['apt']
    - name: oh_my_zsh
      tags: ['oh-my-zsh']
      become_user: "{{ user }}"
    - name: dotfiles
      tags: ['dotfiles']
      become_user: "{{ user }}"
  environment:
    - "{{ proxy_env | default ({}) }}"

- hosts: home_server
  tags:
    - home_server_tools
  roles:
    - name: nas
      tags: [ 'nas' ]
    - name: mailer
      tags: [ 'mailer' ]
    - name: scheduled_tasks
      tags: [ 'scheduled_tasks' ]
    - name: web_privacy_proxy
      tags: [ 'web_privacy_proxy' ]
    - name: authenticator
      tags: [ 'mfa' ]
  environment:
    - "{{ proxy_env | default ({}) }}"

- hosts: devbox
  tags:
    - devbox
  roles:
    - name: docker
      tags: [ 'docker' ]
    - name: java
      tags: [ 'java' ]
    - name: nodejs
      tags: [ 'nodejs' ]
      become_user: "{{ user }}"
  environment:
    - "{{ proxy_env | default ({}) }}"

