# vi: set ft=ansible :

- hosts: commons
  tags:
    - base
  roles:
    - { role: base, tags: [ 'apt' ] }
    - { role: oh_my_zsh, tags: [ 'oh-my-zsh' ], become: yes, become_user: "{{ user }}" }
    - { role: dotfiles, tags: [ 'dotfiles' ], become: yes, become_user: "{{ user }}" }
  environment:
    - "{{ proxy_env }}"

- hosts: homeserver 
  tags:
    - nas
  roles:
    - nas
  environment:
    - "{{ proxy_env }}"

- hosts: devbox
  tags:
    - devbox
  roles:
    - { role: docker, tags: [ 'docker' ] }
    - { role: nodejs, tags: [ 'nodejs' ], become: yes, become_user: "{{ user }}" }
  environment:
    - "{{ proxy_env }}"

