- name: Install requirements
  apt:
    name:
      - oathtool
    state: present

- name: Creating /home/{{ user }}/bin/ directory
  file:
    path: /home/{{ user }}/bin
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Create mfa script
  template:
    src: authenticator.sh.j2
    dest: "/home/{{ user }}/bin/authenticator.sh"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0770
  when: mfa is defined

