- name: Update cache before install
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install requirements and tools packages
  apt: name={{ item }} state=present
  with_items:
  - apt-transport-https

- name: Add sublime official GPG key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Check if repo file already exists
  lineinfile:
    path: /etc/apt/sources.list.d/sublime-text.list
    line: deb https://download.sublimetext.com/ apt/stable/
    create: yes

- name: Install sublime-text
  apt: name=sublime-text state=present update_cache=yes

