- name: Creating /home/{{ user }}/bin/ directory
  file: path=/home/{{ user }}/bin state=directory

- name: Check if intellij idea already exists
  stat:
    path: /home/{{ user }}/bin/idea.sh
  register:
    intellij_bin

- name: Downloading intellij idea {{ intellij_version }}
  get_url:
    url: https://download.jetbrains.com/idea/ideaI{{ intellij_version }}.tar.gz
    dest: /home/{{ user }}/bin/ideaI{{ intellij_version }}.tar.gz
    checksum: "{{ intellij_checksum }}"
  when: intellij_bin.stat.islnk is not defined

- name: Extracting intellij idea
  unarchive:
    remote_src: yes
    src: /home/{{ user }}/bin/ideaI{{ intellij_version }}.tar.gz
    dest: /home/{{ user }}/bin
  when: intellij_bin.stat.islnk is not defined

- name: Removing downloaded zip
  file:
    state: absent
    path: /home/{{ user }}/bin/ideaI{{ intellij_version }}.tar.gz

- name: Get extracted name
  command: find /home/{{ user }}/bin -type d -name "idea-IU-*"
  register: intellij_extracted_name

- name: Creating symlinks for node-linux-{{ node_arch }}
  file:
    src: "{{ intellij_extracted_name.stdout_lines[0] + '/bin/idea.sh' }}"
    dest: /home/{{ user }}/bin/idea.sh
    state: link

