- name: Cloning my dotfiles
  git:
    repo: 'https://github.com/xaviermichel/dotfiles.git'
    dest: /home/{{ user }}/.dotfiles
    update: no

- name: Clone zsh suggestion plugin
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: /home/{{ user }}/.oh-my-zsh/plugins/zsh-autosuggestions

- name: Bootstrap dotfiles
  shell: script/bootstrap
  args:
    chdir: /home/{{ user }}/.dotfiles

- name: Downloading custom theme
  get_url:
    url: https://gist.githubusercontent.com/xaviermichel/5635753/raw/simple.zsh-theme
    dest: /home/{{ user }}/.oh-my-zsh/themes/xavier-simple.zsh-theme

- name: Configuring default theme
  replace:
    path: /home/{{ user }}/.zshrc
    regexp: 'ZSH_THEME=".*"'
    replace: 'ZSH_THEME="xavier-simple"'

- name: Ensures "/home/{{ user }}/.vim/..." dir exists
  file: path=/home/{{ user }}/.vim/{{ item }} state=directory
  with_items:
    - bundle
    - temp
    - backup

- name: Install vim plugin manager
  git:
    repo: https://github.com/gmarik/vundle.git
    dest: /home/{{ user }}/.vim/bundle/vundle/

- name: Print installation message
  debug:
    msg: You can complete installation with $ vim +PluginInstall +qall

- name: Creating /home/{{ user }}/.ssh directory
  file: path=/home/{{ user }}/.ssh state=directory

- name: Check if ssh config already exists
  stat:
    path: /home/{{ user }}/.ssh/config
  register:
    ssh_config

- name: Copy file with owner and permissions
  copy:
    src: "{{ item }}"
    dest: "/home/{{ user }}/.{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'
  with_items:
    - byobu

#- name: Copy local home ssh conf
#  copy:
#    src: ssh/home_local_config
#    dest: /home/{{ user }}/.ssh/config
#  when: ssh_config.stat.exists is defined and ssh_config.stat.exists == False and 'devbox-server-home' in group_names


