- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install Kubernetes tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubectl
      - jq

- name: Clone kubens/kubectx repo
  git:
    repo: https://github.com/ahmetb/kubectx
    dest: /opt/kubectx

- name: Create kubens/kubectx symlinks
  file:
    src: /opt/kubectx/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    state: link
  with_items:
    - kubectx
    - kubens

- name: Install k9s
  include_tasks: ../../commons/tasks/get_github_binary.yml
  vars:
    package_name: k9s
    package_binary: k9s
    package_overwrite_existing: "{{ k9s_overwrite_existing | default(k8s_tools_overwrite_existing) }}"
    package_version: "{{ k9s_version | default(k8s_tools_version) }}"
    package_repository: derailed/k9s
    package_release_filename: k9s_Linux_{{ ansible_architecture }}

- name: Install df-pv
  include_tasks: ../../commons/tasks/get_github_binary.yml
  vars:
    package_name: df-pv
    package_binary: df-pv
    package_overwrite_existing: "{{ k9s_overwrite_existing | default(k8s_tools_overwrite_existing) }}"
    package_version: "{{ df_pv_version | default(k8s_tools_version) }}"
    package_repository: yashbhutwala/kubectl-df-pv
    package_release_filename: 'kubectl-df-pv_@VERSION_linux_amd64'

- name: Install stern
  include_tasks: ../../commons/tasks/get_github_binary.yml
  vars:
    package_name: stern
    package_binary: stern
    package_overwrite_existing: "{{ stern_overwrite_existing | default(k8s_tools_overwrite_existing) }}"
    package_version: "{{ stern_version | default(k8s_tools_version) }}"
    package_repository: wercker/stern
    package_release_filename: 'stern_linux_amd64'
    package_release_format: ''
    package_is_archive: false

- name: Install tkn
  include_tasks: ../../commons/tasks/get_github_binary.yml
  vars:
    package_name: tkn
    package_binary: tkn
    package_overwrite_existing: "{{ tkn_overwrite_existing | default(k8s_tools_overwrite_existing) }}"
    package_version: "{{ tkn_version | default(k8s_tools_version) }}"
    package_repository: tektoncd/cli
    package_release_filename: 'tkn_@VERSION_Linux_x86_64'
    package_version_mutation: '| sed "s/^v\(.*\)/\1/"'

- name: Install ytt
  include_tasks: ../../commons/tasks/get_github_binary.yml
  vars:
    package_name: ytt
    package_binary: ytt
    package_overwrite_existing: "{{ ytt_overwrite_existing | default(k8s_tools_overwrite_existing) }}"
    package_version: "{{ ytt_version | default(k8s_tools_version) }}"
    package_repository: vmware-tanzu/carvel-ytt
    package_release_filename: ytt-linux-amd64
    package_release_format: ''
    package_is_archive: false

