- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Install Kubernetes tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubectl

- name: Clone kubens/kubectx repo
  git:
    repo: https://github.com/ahmetb/kubectx
    dest: /opt/kubectx

- name: Create kubens/kubectx symlinks
  file:
    src: /opt/kubectx/{{ item }}
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    state: link
  with_items:
    - kubectx
    - kubens

- name: check for k9s installation
  stat:
    path: '/usr/local/bin/k9s'
  changed_when: false
  register: k9s_binary
- when: not k9s_binary.stat.exists or k9s_overwrite_existing
  block:
    - name: Download k9s
      get_url:
        url: 'https://github.com/derailed/k9s/releases/download/v{{ k9s_version }}/k9s_Linux_{{ ansible_architecture }}.tar.gz'
        dest: '/tmp/k9s.tar.gz'
        mode: '0644'
    - name: Unpack k9s
      unarchive:
        remote_src: yes
        src: '/tmp/k9s.tar.gz'
        dest: '/usr/local/bin'
        creates: '/usr/local/bin/k9s'
        owner: root
        group: root
        exclude:
          - README.md
          - LICENCE
  always:
    - name: Cleanup temp files
      file:
        dest: '/tmp/k9s.tar.gz'
        state: absent

- name: check for df-pv installation
  stat:
    path: '/usr/local/bin/df-pv'
  changed_when: false
  register: df_pv_binary
- when: not df_pv_binary.stat.exists or df_pv_overwrite_existing
  block:
    - name: Download df-pv
      get_url:
        url: 'https://github.com/yashbhutwala/kubectl-df-pv/releases/download/v{{ df_pv_version }}/kubectl-df-pv_v{{ df_pv_version }}_linux_amd64.tar.gz'
        dest: '/tmp/df-pv.tar.gz'
        mode: '0644'
    - name: Unpack df-pv
      unarchive:
        remote_src: yes
        src: '/tmp/df-pv.tar.gz'
        dest: '/usr/local/bin'
        creates: '/usr/local/bin/df-pv'
        owner: root
        group: root
        exclude:
          - README.md
          - LICENCE
  always:
    - name: Cleanup temp files
      file:
        dest: '/tmp/df-pv.tar.gz'
        state: absent

