- name: Install tools
  apt:
    name:
      - iptables-persistent
      - squid
      - openvpn
      - openssl
      - easy-rsa
      - redsocks
      - dnsmasq
    state: present
    update_cache: yes
  register: apt_openvpn

- name: Print end of openvpn installation message
  debug:
    msg: You may now restore openvpn conf
  when: apt_openvpn.changed

- name: Copy redsocks configuration
  copy:
    src: "redsocks.conf"
    dest: "/etc/redsocks.conf"
    owner: "root"
    group: "root"
    mode: '0644'
  notify: reload redsocks

- name: Create DNS blacklists directory
  file:
    path: /etc/dnsmasq/blacklists
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: "0755"

# https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh
- name: Download DNS blacklists
  get_url:
    url: "{{ item }}"
    dest: /etc/dnsmasq/blacklists/
    mode: "0644"
  with_items:
    - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
    #- https://hosts-file.net/ad_servers.txt

- name: Assemble sub blacklists
  assemble:
    src: /etc/dnsmasq/blacklists/
    dest: /etc/dnsmasq/blacklist.txt

- name: Copy dnsmasq configuration
  template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart dnsmasq

- name: Set ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes

- name: Block access from VPN to local network
  iptables:
    table: filter
    chain: "{{ item }}"
    in_interface: tun0
    destination: "192.168.1.0/24"
    jump: REJECT
  with_items:
    - INPUT
    - FORWARD
  notify: iptables save

- name: Proxify HTTP traffic
  iptables:
    table: nat
    protocol: tcp
    chain: PREROUTING
    in_interface: tun0
    source: "!10.18.0.1"
    destination: "!10.18.0.1/24"
    jump: REDIRECT
    destination_port: "80"
    to_ports: "31281"
  notify: iptables save

- name: Proxify HTTPs traffic
  iptables:
    table: nat
    protocol: tcp
    chain: PREROUTING
    in_interface: tun0
    source: "!10.18.0.1"
    destination: "!10.18.0.1/24"
    jump: REDIRECT
    to_ports: "31282"
  notify: iptables save

