- name: Add an apt signing key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Adding apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: terraform

- name: Install
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - terraform

