- name: iptables save
  become: true
  shell: netfilter-persistent save

- name: reload redsocks
  service:
    name: redsocks
    state: restarted

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

