- name: Create scheduler tasks directory
  file:
    path: /home/{{ user }}/tasks
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'
    state: directory

- name: Deploy scheduled tasks scripts
  include_tasks: deploy_task.yml
  with_items:
    - { task: 'duckdns', file: 'duckdns.sh', cron_min: '0' }
    - { task: 'detect_train_delay', file: 'detect_train_delay.sh', cron_weekday: '1-5', cron_hour: '7', cron_min: '20' }

- name: Configure cron for already deployed scripts
  include_tasks: deploy_cron_for_bin.yml
  with_items:
    - { task: 'monitoring', file: 'monitoring.sh', cron_hour: '*/6', cron_min: '0' }
    - { task: 'web_checker', file: 'web_checker.sh', cron_hour: '8-22', cron_min: '0', cron_disabled: no}

- name: Nextcloud tasks
  include_tasks: deploy_simple_task.yml
  with_items:
    - { task: 'nextcloud_webcron', cron_min: '*/5', job: 'docker exec --user www-data nextcloud_nextcloud_1 php -f /var/www/html/cron.php'}
    - { task: 'nextcloud_face_recognition', disabled: 'yes', cron_hour: '4', cron_min: '0', job: 'docker exec --user www-data nextcloud_nextcloud_1 ./occ face:background_job >/dev/null 2>&1'}

