- name: Update cache before install
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install requirements and tools packages
  apt: name={{ item }} state=present
  with_items:
  - guake

