- name: Creating /home/{{ user }}/bin/ directory
  file: path=/home/{{ user }}/bin state=directory

- name: Update cache before install
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  become_user: root

- name: Install requirements and tools packages
  apt: name={{ item }} state=present
  with_items:
  - make
  - g++
  become: yes
  become_user: root

- name: Check if node {{ node_version }} already exists
  stat:
    path: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}/bin/node
  register:
    node_bin

- name: Downloading node {{ node_version }} for arch {{ node_arch }}
  get_url:
    url: https://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz
    dest: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz
  when: node_bin.stat.exists is defined and node_bin.stat.exists == False

- name: Extracting node directory
  unarchive:
    remote_src: yes
    src: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz
    dest: /home/{{ user }}/bin
  when: node_bin.stat.exists is defined and node_bin.stat.exists == False

- name: Remove downloaded zip
  file:
    state: absent
    path: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz

- name: Creating symlinks for node-linux-{{ node_arch }}
  file:
    src: node-{{ node_version }}-linux-{{ node_arch }}
    dest: /home/{{ user }}/bin/node-linux
    state: link

- block:
  - name: Installing node usefull packages
    npm:
      name: "{{ item }}"
      global: yes
    with_items:
      - bower
      - gulp
      - http-server
      - yarn
  environment:
    - PATH: ${PATH}:/home/{{ user }}/bin:/home/{{ user }}/bin/node-linux/bin


