- name: Creating /home/{{ user }}/bin/ directory
  file: path=/home/{{ user }}/bin state=directory

- name: Check if node {{ node_version }} already exists
  stat:
    path: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}/bin/node
  register:
    node_bin

- name: Downloading node {{ node_version }} for arch {{ node_arch }}
  get_url:
    url: https://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz
    dest: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz
  when: node_bin.stat.exists is defined and node_bin.stat.exists == False

- name: Extracting node directory
  unarchive:
    remote_src: yes
    src: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz
    dest: /home/{{ user }}/bin
  when: node_bin.stat.exists is defined and node_bin.stat.exists == False

- name: Remove downloaded zip
  file:
    state: absent
    path: /home/{{ user }}/bin/node-{{ node_version }}-linux-{{ node_arch }}.tar.xz

- name: Creating symlinks for node-linux-{{ node_arch }}
  file:
    src: node-{{ node_version }}-linux-{{ node_arch }}
    dest: /home/{{ user }}/bin/node-linux
    state: link

- name: Creating symlinks for node
  file:
    src: node-linux/bin/node
    dest: /home/{{ user }}/bin/node
    state: link

- name: Creating symlinks for npm
  file:
    src: node-linux/bin/npm
    dest: /home/{{ user }}/bin/npm
    state: link

- block:
  - name: Installing node usefull packages
    npm:
      name: "{{ item }}"
      global: yes
    with_items:
      - bower
      - gulp
      - http-server
      - yarn
      - casperjs
  - name: Link installed package
    file:
      src: node-linux/bin/{{ item }}
      dest: /home/{{ user }}/bin/{{ item }}
      state: link
    with_items:
      - bower
      - gulp
      - http-server
      - yarn
      - casperjs
  environment:
    - PATH: ${PATH}:/home/{{ user }}/bin

