- name: Install requirements and tools packages
  apt:
    name:
      - git
      - jq
      - htop
      - dfc
      - vim
      - zsh
      - tmux
      - byobu
      - zip
      - unzip
      - bzip2
      - fontconfig
      - curl
      - fail2ban
      - ccze
      - httpie
      - tree
      - rsync
      - net-tools
      - tcpdump
      - dnsutils
      - telnet
    state: present
    update_cache: yes

- name: Disable ssh for root user
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PermitRootLogin no
    insertafter: "^#PermitRootLogin "
  notify:
    - reload sshd

- name: Create all unix users accounts
  user:
    name: "{{ item }}"
    create_home: no
    shell: /sbin/nologin
    append: yes
    state: present
  with_items: "{{ users.unix.technical }}"
  when: users.unix.technical is defined

- name: Copy configurations files
  copy:
    src: "{{ secrets_conf_root }}/files/{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "{{ item.mode | default('0644') }}"
    force: no
  with_items: "{{ files }}"
  when: files is defined

