- name: Install requirements and tools packages
  apt:
    name:
      - git
      - jq
      - htop
      - dfc
      - vim
      - zsh
      - tmux
      - byobu
      - zip
      - unzip
      - bzip2
      - fontconfig
      - curl
      - fail2ban
      - ccze
      - httpie
      - tree
      - rsync
      - net-tools
      - tcpdump
      - dnsutils
    state: present
    update_cache: yes

- name: Upgrade all packages
  apt:
    upgrade: yes

- name: Disable ssh for root user
  lineinfile:
    path: /etc/ssh/sshd_config
    line: PermitRootLogin no
    insertafter: "^#PermitRootLogin "
  notify:
    - reload sshd

- name: Check if {{ secrets_vars_file }} script exists
  stat:
    path: "{{ secrets_vars_file }}"
  register: secret_file

- name: Include secret vars
  include_vars:
    file: "{{ secrets_vars_file }}"
    name: secrets
  when: secret_file.stat.exists == True

- name: Create all unix users accounts
  user:
    name: "{{ item }}"
    create_home: no
    shell: /sbin/nologin
    append: yes
    state: present
  with_items: "{{ secrets.users.unix.technical }}"
  when: secret_file.stat.exists == True

