- name: Creating /home/{{ user }}/bin/ directory
  file: path=/home/{{ user }}/bin state=directory

- name: Check if terraform already exists
  stat:
    path: /home/{{ user }}/bin/terraform
  register:
    terraform_bin

- name: Downloading terraform {{ terraform_version }}
  get_url:
    url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /home/{{ user }}/bin/terraform_{{ terraform_version }}_linux_amd64.zip
  when: terraform_bin.stat.exists is defined and terraform_bin.stat.exists == False

- name: Extracting terraform
  unarchive:
    remote_src: yes
    src: /home/{{ user }}/bin/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: /home/{{ user }}/bin
  when: terraform_bin.stat.exists is defined and terraform_bin.stat.exists == False

- name: Remove downloaded zip
  file:
    state: absent
    path: /home/{{ user }}/bin/terraform_{{ terraform_version }}_linux_amd64.zip

